In [23]:
# Import Dependencies
import requests
import pandas as pd
from pprint import pprint
from datetime import datetime as dt
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
# Make an API call to the database 
url = "https://data.sfgov.org/resource/ubvf-ztfx.json"
response = requests.get(url)
data = response.json()

In [3]:
type(data)

list

In [4]:
len(data)

1000

In [5]:
pprint(data[10])

{':@computed_region_26cr_cadq': '9',
 ':@computed_region_6qbp_sg9q': '55',
 ':@computed_region_ajp5_b2md': '26',
 ':@computed_region_jwn9_ihcz': '55',
 ':@computed_region_qgnn_b9vv': '2',
 'accident_year': '2020',
 'beat_number': '3C11D',
 'case_id_pkey': '200325422',
 'cnn_intrsctn_fkey': '23555000',
 'cnn_sgmt_fkey': '191101',
 'collision_date': '2020-05-29T00:00:00.000',
 'collision_datetime': '2020-05-29T16:52:00.000',
 'collision_severity': 'Injury (Other Visible)',
 'collision_time': '16:52:00',
 'control_device': 'Functioning',
 'data_as_of': '2020-06-04T00:00:00.000',
 'data_loaded_at': '2023-07-29T03:30:14.844',
 'data_updated_at': '2023-04-06T00:00:00.000',
 'day_of_week': 'Friday',
 'direction': 'South',
 'distance': '228',
 'dph_col_grp': 'AA',
 'dph_col_grp_description': 'Vehicle(s) Only Involved',
 'geocode_location': 'CITY STREET',
 'geocode_source': 'SFPD-INTERIM DB',
 'intersection': 'Midblock > 20ft',
 'juris': '3801',
 'lighting': 'Daylight',
 'month': 'May',
 'mviw': 'Non-Collision',
 'number_injured': '1',
 'number_killed': '0',
 'officer_id': '1858',
 'party1_dir_of_travel': 'South',
 'party1_move_pre_acc': 'Proceeding Straight',
 'party1_type': 'Driver',
 'ped_action': 'No Pedestrian Involved',
 'point': {'coordinates': [-122.38816, 37.757336], 'type': 'Point'},
 'primary_rd': '03RD ST',
 'reporting_district': 'Bayview',
 'road_cond_1': 'No Unusual Condition',
 'road_cond_2': 'Not Stated',
 'road_surface': 'Dry',
 'secondary_rd': '22ND ST',
 'street_view': 'https://maps.google.com/maps?q=&layer=c&cbll=37.7573355575,-122.388164094',
 'tb_latitude': '37.7573355575',
 'tb_longitude': '-122.388164094',
 'time_cat': '2:01 pm to 6:00 pm',
 'type_of_collision': 'Not Stated',
 'unique_id': '52962',
 'vz_pcf_code': 'Other Than Driver',
 'vz_pcf_description': 'Unknown',
 'vz_pcf_group': 'Other Than Driver',
 'weather_1': 'Clear',
 'weather_2': 'Not Stated'}

In [6]:
# convert to data frame
df = pd.DataFrame(data)
df.head()

,unique_id,cnn_intrsctn_fkey,case_id_pkey,tb_latitude,tb_longitude,geocode_source,geocode_location,collision_datetime,collision_date,collision_time,...,data_as_of,data_updated_at,data_loaded_at,:@computed_region_jwn9_ihcz,:@computed_region_6qbp_sg9q,:@computed_region_qgnn_b9vv,:@computed_region_26cr_cadq,:@computed_region_ajp5_b2md,party_at_fault,cnn_sgmt_fkey
0,15414,23926000,151003670,37.7778565368195,-122.406436335616,SFPD-CROSSROADS,CITY STREET,2015-11-18T09:04:00.000,2015-11-18T00:00:00.000,09:04:00,...,2015-11-18T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:11.790,32,32,1,10,34,NaN,NaN
1,52640,23969000,200212108,37.7544528719,-122.408342784,SFPD-INTERIM DB,CITY STREET,2020-03-28T14:35:00.000,2020-03-28T00:00:00.000,14:35:00,...,2020-04-02T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.446,53,53,3,2,20,1,NaN
2,36577,22495000,140836694,37.7140400777839,-122.461135168136,SFPD-CROSSROADS,CITY STREET,2014-10-04T13:25:00.000,2014-10-04T00:00:00.000,13:25:00,...,2014-10-04T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.468,81,81,10,1,24,NaN,5408000
3,27582,24726000,160732947,37.7916270504119,-122.402515531378,SFPD-CROSSROADS,CITY STREET,2016-09-08T14:00:00.000,2016-09-08T00:00:00.000,14:00:00,...,2016-09-08T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.500,108,108,6,3,8,NaN,9299000
4,14911,23811000,180566685,37.7798561436,-122.394007535,SFPD-INTERIM DB,CITY STREET,2018-07-30T11:25:00.000,2018-07-30T00:00:00.000,11:25:00,...,2018-10-22T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:14.634,31,31,1,10,8,NaN,179000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 60 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   unique_id                    1000 non-null   object
 1   cnn_intrsctn_fkey            1000 non-null   object
 2   case_id_pkey                 1000 non-null   object
 3   tb_latitude                  980 non-null    object
 4   tb_longitude                 980 non-null    object
 5   geocode_source               1000 non-null   object
 6   geocode_location             1000 non-null   object
 7   collision_datetime           1000 non-null   object
 8   collision_date               1000 non-null   object
 9   collision_time               996 non-null    object
 10  accident_year                1000 non-null   object
 11  month                        1000 non-null   object
 12  day_of_week                  1000 non-null   object
 13  time_cat                     996 non-null    object
 14  juris                        1000 non-null   object
 15  officer_id                   986 non-null    object
 16  reporting_district           861 non-null    object
 17  beat_number                  912 non-null    object
 18  primary_rd                   1000 non-null   object
 19  secondary_rd                 986 non-null    object
 20  distance                     987 non-null    object
 21  direction                    1000 non-null   object
 22  weather_1                    1000 non-null   object
 23  weather_2                    990 non-null    object
 24  collision_severity           1000 non-null   object
 25  type_of_collision            1000 non-null   object
 26  mviw                         1000 non-null   object
 27  ped_action                   1000 non-null   object
 28  road_surface                 1000 non-null   object
 29  road_cond_1                  1000 non-null   object
 30  road_cond_2                  1000 non-null   object
 31  lighting                     1000 non-null   object
 32  control_device               1000 non-null   object
 33  intersection                 1000 non-null   object
 34  vz_pcf_code                  1000 non-null   object
 35  vz_pcf_group                 987 non-null    object
 36  vz_pcf_description           1000 non-null   object
 37  vz_pcf_link                  899 non-null    object
 38  number_killed                1000 non-null   object
 39  number_injured               1000 non-null   object
 40  street_view                  981 non-null    object
 41  dph_col_grp                  1000 non-null   object
 42  dph_col_grp_description      1000 non-null   object
 43  party1_type                  998 non-null    object
 44  party1_dir_of_travel         998 non-null    object
 45  party1_move_pre_acc          998 non-null    object
 46  party2_type                  741 non-null    object
 47  party2_dir_of_travel         741 non-null    object
 48  party2_move_pre_acc          741 non-null    object
 49  point                        980 non-null    object
 50  data_as_of                   1000 non-null   object
 51  data_updated_at              1000 non-null   object
 52  data_loaded_at               1000 non-null   object
 53  :@computed_region_jwn9_ihcz  968 non-null    object
 54  :@computed_region_6qbp_sg9q  968 non-null    object
 55  :@computed_region_qgnn_b9vv  978 non-null    object
 56  :@computed_region_26cr_cadq  979 non-null    object
 57  :@computed_region_ajp5_b2md  978 non-null    object
 58  party_at_fault               440 non-null    object
 59  cnn_sgmt_fkey                552 non-null    object
dtypes: object(60)
memory usage: 468.9+ KB

In [9]:
# drop any rows that do not have a collision time
df = df[df['collision_time'].notna()]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 996 entries, 0 to 999
Data columns (total 60 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   unique_id                    996 non-null    object
 1   cnn_intrsctn_fkey            996 non-null    object
 2   case_id_pkey                 996 non-null    object
 3   tb_latitude                  977 non-null    object
 4   tb_longitude                 977 non-null    object
 5   geocode_source               996 non-null    object
 6   geocode_location             996 non-null    object
 7   collision_datetime           996 non-null    object
 8   collision_date               996 non-null    object
 9   collision_time               996 non-null    object
 10  accident_year                996 non-null    object
 11  month                        996 non-null    object
 12  day_of_week                  996 non-null    object
 13  time_cat                     996 non-null    object
 14  juris                        996 non-null    object
 15  officer_id                   983 non-null    object
 16  reporting_district           857 non-null    object
 17  beat_number                  908 non-null    object
 18  primary_rd                   996 non-null    object
 19  secondary_rd                 982 non-null    object
 20  distance                     983 non-null    object
 21  direction                    996 non-null    object
 22  weather_1                    996 non-null    object
 23  weather_2                    986 non-null    object
 24  collision_severity           996 non-null    object
 25  type_of_collision            996 non-null    object
 26  mviw                         996 non-null    object
 27  ped_action                   996 non-null    object
 28  road_surface                 996 non-null    object
 29  road_cond_1                  996 non-null    object
 30  road_cond_2                  996 non-null    object
 31  lighting                     996 non-null    object
 32  control_device               996 non-null    object
 33  intersection                 996 non-null    object
 34  vz_pcf_code                  996 non-null    object
 35  vz_pcf_group                 983 non-null    object
 36  vz_pcf_description           996 non-null    object
 37  vz_pcf_link                  895 non-null    object
 38  number_killed                996 non-null    object
 39  number_injured               996 non-null    object
 40  street_view                  978 non-null    object
 41  dph_col_grp                  996 non-null    object
 42  dph_col_grp_description      996 non-null    object
 43  party1_type                  994 non-null    object
 44  party1_dir_of_travel         994 non-null    object
 45  party1_move_pre_acc          994 non-null    object
 46  party2_type                  737 non-null    object
 47  party2_dir_of_travel         737 non-null    object
 48  party2_move_pre_acc          737 non-null    object
 49  point                        977 non-null    object
 50  data_as_of                   996 non-null    object
 51  data_updated_at              996 non-null    object
 52  data_loaded_at               996 non-null    object
 53  :@computed_region_jwn9_ihcz  966 non-null    object
 54  :@computed_region_6qbp_sg9q  966 non-null    object
 55  :@computed_region_qgnn_b9vv  975 non-null    object
 56  :@computed_region_26cr_cadq  976 non-null    object
 57  :@computed_region_ajp5_b2md  975 non-null    object
 58  party_at_fault               438 non-null    object
 59  cnn_sgmt_fkey                551 non-null    object
dtypes: object(60)
memory usage: 474.7+ KB

In [10]:
# drop any rows that do not have a lat and lon
df = df[df['tb_latitude'].notna()]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 977 entries, 0 to 999
Data columns (total 60 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   unique_id                    977 non-null    object
 1   cnn_intrsctn_fkey            977 non-null    object
 2   case_id_pkey                 977 non-null    object
 3   tb_latitude                  977 non-null    object
 4   tb_longitude                 977 non-null    object
 5   geocode_source               977 non-null    object
 6   geocode_location             977 non-null    object
 7   collision_datetime           977 non-null    object
 8   collision_date               977 non-null    object
 9   collision_time               977 non-null    object
 10  accident_year                977 non-null    object
 11  month                        977 non-null    object
 12  day_of_week                  977 non-null    object
 13  time_cat                     977 non-null    object
 14  juris                        977 non-null    object
 15  officer_id                   965 non-null    object
 16  reporting_district           842 non-null    object
 17  beat_number                  893 non-null    object
 18  primary_rd                   977 non-null    object
 19  secondary_rd                 977 non-null    object
 20  distance                     977 non-null    object
 21  direction                    977 non-null    object
 22  weather_1                    977 non-null    object
 23  weather_2                    968 non-null    object
 24  collision_severity           977 non-null    object
 25  type_of_collision            977 non-null    object
 26  mviw                         977 non-null    object
 27  ped_action                   977 non-null    object
 28  road_surface                 977 non-null    object
 29  road_cond_1                  977 non-null    object
 30  road_cond_2                  977 non-null    object
 31  lighting                     977 non-null    object
 32  control_device               977 non-null    object
 33  intersection                 977 non-null    object
 34  vz_pcf_code                  977 non-null    object
 35  vz_pcf_group                 964 non-null    object
 36  vz_pcf_description           977 non-null    object
 37  vz_pcf_link                  876 non-null    object
 38  number_killed                977 non-null    object
 39  number_injured               977 non-null    object
 40  street_view                  977 non-null    object
 41  dph_col_grp                  977 non-null    object
 42  dph_col_grp_description      977 non-null    object
 43  party1_type                  977 non-null    object
 44  party1_dir_of_travel         977 non-null    object
 45  party1_move_pre_acc          977 non-null    object
 46  party2_type                  724 non-null    object
 47  party2_dir_of_travel         724 non-null    object
 48  party2_move_pre_acc          724 non-null    object
 49  point                        977 non-null    object
 50  data_as_of                   977 non-null    object
 51  data_updated_at              977 non-null    object
 52  data_loaded_at               977 non-null    object
 53  :@computed_region_jwn9_ihcz  966 non-null    object
 54  :@computed_region_6qbp_sg9q  966 non-null    object
 55  :@computed_region_qgnn_b9vv  975 non-null    object
 56  :@computed_region_26cr_cadq  976 non-null    object
 57  :@computed_region_ajp5_b2md  975 non-null    object
 58  party_at_fault               423 non-null    object
 59  cnn_sgmt_fkey                535 non-null    object
dtypes: object(60)
memory usage: 465.6+ KB

In [11]:
# convert collision date to datetime data type
df['collision_datetime'] = pd.to_datetime(df['collision_date'])
df.head()

,unique_id,cnn_intrsctn_fkey,case_id_pkey,tb_latitude,tb_longitude,geocode_source,geocode_location,collision_datetime,collision_date,collision_time,...,data_as_of,data_updated_at,data_loaded_at,:@computed_region_jwn9_ihcz,:@computed_region_6qbp_sg9q,:@computed_region_qgnn_b9vv,:@computed_region_26cr_cadq,:@computed_region_ajp5_b2md,party_at_fault,cnn_sgmt_fkey
0,15414,23926000,151003670,37.7778565368195,-122.406436335616,SFPD-CROSSROADS,CITY STREET,2015-11-18,2015-11-18T00:00:00.000,09:04:00,...,2015-11-18T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:11.790,32,32,1,10,34,NaN,NaN
1,52640,23969000,200212108,37.7544528719,-122.408342784,SFPD-INTERIM DB,CITY STREET,2020-03-28,2020-03-28T00:00:00.000,14:35:00,...,2020-04-02T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.446,53,53,3,2,20,1,NaN
2,36577,22495000,140836694,37.7140400777839,-122.461135168136,SFPD-CROSSROADS,CITY STREET,2014-10-04,2014-10-04T00:00:00.000,13:25:00,...,2014-10-04T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.468,81,81,10,1,24,NaN,5408000
3,27582,24726000,160732947,37.7916270504119,-122.402515531378,SFPD-CROSSROADS,CITY STREET,2016-09-08,2016-09-08T00:00:00.000,14:00:00,...,2016-09-08T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.500,108,108,6,3,8,NaN,9299000
4,14911,23811000,180566685,37.7798561436,-122.394007535,SFPD-INTERIM DB,CITY STREET,2018-07-30,2018-07-30T00:00:00.000,11:25:00,...,2018-10-22T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:14.634,31,31,1,10,8,NaN,179000

In [14]:
# convert collision time to datetime data type keep only hour
df['collision_time'] = pd.to_datetime(df['collision_time'], format='%H:%M').dt.hour
df.head()

,unique_id,cnn_intrsctn_fkey,case_id_pkey,tb_latitude,tb_longitude,geocode_source,geocode_location,collision_datetime,collision_date,collision_time,...,data_as_of,data_updated_at,data_loaded_at,:@computed_region_jwn9_ihcz,:@computed_region_6qbp_sg9q,:@computed_region_qgnn_b9vv,:@computed_region_26cr_cadq,:@computed_region_ajp5_b2md,party_at_fault,cnn_sgmt_fkey
0,15414,23926000,151003670,37.7778565368195,-122.406436335616,SFPD-CROSSROADS,CITY STREET,2015-11-18,2015-11-18T00:00:00.000,9,...,2015-11-18T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:11.790,32,32,1,10,34,NaN,NaN
1,52640,23969000,200212108,37.7544528719,-122.408342784,SFPD-INTERIM DB,CITY STREET,2020-03-28,2020-03-28T00:00:00.000,14,...,2020-04-02T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.446,53,53,3,2,20,1,NaN
2,36577,22495000,140836694,37.7140400777839,-122.461135168136,SFPD-CROSSROADS,CITY STREET,2014-10-04,2014-10-04T00:00:00.000,13,...,2014-10-04T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.468,81,81,10,1,24,NaN,5408000
3,27582,24726000,160732947,37.7916270504119,-122.402515531378,SFPD-CROSSROADS,CITY STREET,2016-09-08,2016-09-08T00:00:00.000,14,...,2016-09-08T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:13.500,108,108,6,3,8,NaN,9299000
4,14911,23811000,180566685,37.7798561436,-122.394007535,SFPD-INTERIM DB,CITY STREET,2018-07-30,2018-07-30T00:00:00.000,11,...,2018-10-22T00:00:00.000,2023-04-26T00:00:00.000,2023-07-29T03:30:14.634,31,31,1,10,8,NaN,179000

In [19]:
# convert injury number columns to integer types as well as year column 
integer_col = ['accident_year','number_killed', 'number_injured']
df[integer_col]=df[integer_col].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 977 entries, 0 to 999
Data columns (total 61 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   unique_id                    977 non-null    object
 1   cnn_intrsctn_fkey            977 non-null    object
 2   case_id_pkey                 977 non-null    object
 3   tb_latitude                  977 non-null    float64
 4   tb_longitude                 977 non-null    float64
 5   geocode_source               977 non-null    object
 6   geocode_location             977 non-null    object
 7   collision_datetime           977 non-null    datetime64[ns]
 8   collision_date               977 non-null    object
 9   collision_time               977 non-null    int64
 10  accident_year                977 non-null    int32
 11  month                        977 non-null    object
 12  day_of_week                  977 non-null    object
 13  time_cat                     977 non-null    object
 14  juris                        977 non-null    object
 15  officer_id                   965 non-null    object
 16  reporting_district           842 non-null    object
 17  beat_number                  893 non-null    object
 18  primary_rd                   977 non-null    object
 19  secondary_rd                 977 non-null    object
 20  distance                     977 non-null    object
 21  direction                    977 non-null    object
 22  weather_1                    977 non-null    object
 23  weather_2                    968 non-null    object
 24  collision_severity           977 non-null    object
 25  type_of_collision            977 non-null    object
 26  mviw                         977 non-null    object
 27  ped_action                   977 non-null    object
 28  road_surface                 977 non-null    object
 29  road_cond_1                  977 non-null    object
 30  road_cond_2                  977 non-null    object
 31  lighting                     977 non-null    object
 32  control_device               977 non-null    object
 33  intersection                 977 non-null    object
 34  vz_pcf_code                  977 non-null    object
 35  vz_pcf_group                 964 non-null    object
 36  vz_pcf_description           977 non-null    object
 37  vz_pcf_link                  876 non-null    object
 38  number_killed                977 non-null    int32
 39  number_injured               977 non-null    int32
 40  street_view                  977 non-null    object
 41  dph_col_grp                  977 non-null    object
 42  dph_col_grp_description      977 non-null    object
 43  party1_type                  977 non-null    object
 44  party1_dir_of_travel         977 non-null    object
 45  party1_move_pre_acc          977 non-null    object
 46  party2_type                  724 non-null    object
 47  party2_dir_of_travel         724 non-null    object
 48  party2_move_pre_acc          724 non-null    object
 49  point                        977 non-null    object
 50  data_as_of                   977 non-null    object
 51  data_updated_at              977 non-null    object
 52  data_loaded_at               977 non-null    object
 53  :@computed_region_jwn9_ihcz  966 non-null    object
 54  :@computed_region_6qbp_sg9q  966 non-null    object
 55  :@computed_region_qgnn_b9vv  975 non-null    object
 56  :@computed_region_26cr_cadq  976 non-null    object
 57  :@computed_region_ajp5_b2md  975 non-null    object
 58  party_at_fault               423 non-null    object
 59  cnn_sgmt_fkey                535 non-null    object
 60  period_of_day                964 non-null    category
dtypes: category(1), datetime64[ns](1), float64(2), int32(3), int64(1), object(53)
memory usage: 455.3+ KB

In [20]:
# convert lat and long to float data type
df[['tb_latitude','tb_longitude']] = df[['tb_latitude','tb_longitude']].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 977 entries, 0 to 999
Data columns (total 61 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   unique_id                    977 non-null    object
 1   cnn_intrsctn_fkey            977 non-null    object
 2   case_id_pkey                 977 non-null    object
 3   tb_latitude                  977 non-null    float64
 4   tb_longitude                 977 non-null    float64
 5   geocode_source               977 non-null    object
 6   geocode_location             977 non-null    object
 7   collision_datetime           977 non-null    datetime64[ns]
 8   collision_date               977 non-null    object
 9   collision_time               977 non-null    int64
 10  accident_year                977 non-null    int32
 11  month                        977 non-null    object
 12  day_of_week                  977 non-null    object
 13  time_cat                     977 non-null    object
 14  juris                        977 non-null    object
 15  officer_id                   965 non-null    object
 16  reporting_district           842 non-null    object
 17  beat_number                  893 non-null    object
 18  primary_rd                   977 non-null    object
 19  secondary_rd                 977 non-null    object
 20  distance                     977 non-null    object
 21  direction                    977 non-null    object
 22  weather_1                    977 non-null    object
 23  weather_2                    968 non-null    object
 24  collision_severity           977 non-null    object
 25  type_of_collision            977 non-null    object
 26  mviw                         977 non-null    object
 27  ped_action                   977 non-null    object
 28  road_surface                 977 non-null    object
 29  road_cond_1                  977 non-null    object
 30  road_cond_2                  977 non-null    object
 31  lighting                     977 non-null    object
 32  control_device               977 non-null    object
 33  intersection                 977 non-null    object
 34  vz_pcf_code                  977 non-null    object
 35  vz_pcf_group                 964 non-null    object
 36  vz_pcf_description           977 non-null    object
 37  vz_pcf_link                  876 non-null    object
 38  number_killed                977 non-null    int32
 39  number_injured               977 non-null    int32
 40  street_view                  977 non-null    object
 41  dph_col_grp                  977 non-null    object
 42  dph_col_grp_description      977 non-null    object
 43  party1_type                  977 non-null    object
 44  party1_dir_of_travel         977 non-null    object
 45  party1_move_pre_acc          977 non-null    object
 46  party2_type                  724 non-null    object
 47  party2_dir_of_travel         724 non-null    object
 48  party2_move_pre_acc          724 non-null    object
 49  point                        977 non-null    object
 50  data_as_of                   977 non-null    object
 51  data_updated_at              977 non-null    object
 52  data_loaded_at               977 non-null    object
 53  :@computed_region_jwn9_ihcz  966 non-null    object
 54  :@computed_region_6qbp_sg9q  966 non-null    object
 55  :@computed_region_qgnn_b9vv  975 non-null    object
 56  :@computed_region_26cr_cadq  976 non-null    object
 57  :@computed_region_ajp5_b2md  975 non-null    object
 58  party_at_fault               423 non-null    object
 59  cnn_sgmt_fkey                535 non-null    object
 60  period_of_day                964 non-null    category
dtypes: category(1), datetime64[ns](1), float64(2), int32(3), int64(1), object(53)
memory usage: 455.3+ KB

In [21]:
# bin rows based on hour the incident occured
df_binned = df
bins = [0,4,8,12,16,20,24]
labels = ["12AM - 4AM","4AM - 8AM","8AM - 12PM","12PM - 4PM","4PM - 8PM","8PM - 12AM"]
df_binned['period_of_day'] = pd.cut(x = df_binned['collision_time'], bins = bins, labels = labels)
df_binned.head()

,unique_id,cnn_intrsctn_fkey,case_id_pkey,tb_latitude,tb_longitude,geocode_source,geocode_location,collision_datetime,collision_date,collision_time,...,data_updated_at,data_loaded_at,:@computed_region_jwn9_ihcz,:@computed_region_6qbp_sg9q,:@computed_region_qgnn_b9vv,:@computed_region_26cr_cadq,:@computed_region_ajp5_b2md,party_at_fault,cnn_sgmt_fkey,period_of_day
0,15414,23926000,151003670,37.777857,-122.406436,SFPD-CROSSROADS,CITY STREET,2015-11-18,2015-11-18T00:00:00.000,9,...,2023-04-26T00:00:00.000,2023-07-29T03:30:11.790,32,32,1,10,34,NaN,NaN,8AM - 12PM
1,52640,23969000,200212108,37.754453,-122.408343,SFPD-INTERIM DB,CITY STREET,2020-03-28,2020-03-28T00:00:00.000,14,...,2023-04-26T00:00:00.000,2023-07-29T03:30:13.446,53,53,3,2,20,1,NaN,12PM - 4PM
2,36577,22495000,140836694,37.714040,-122.461135,SFPD-CROSSROADS,CITY STREET,2014-10-04,2014-10-04T00:00:00.000,13,...,2023-04-26T00:00:00.000,2023-07-29T03:30:13.468,81,81,10,1,24,NaN,5408000,12PM - 4PM
3,27582,24726000,160732947,37.791627,-122.402516,SFPD-CROSSROADS,CITY STREET,2016-09-08,2016-09-08T00:00:00.000,14,...,2023-04-26T00:00:00.000,2023-07-29T03:30:13.500,108,108,6,3,8,NaN,9299000,12PM - 4PM
4,14911,23811000,180566685,37.779856,-122.394008,SFPD-INTERIM DB,CITY STREET,2018-07-30,2018-07-30T00:00:00.000,11,...,2023-04-26T00:00:00.000,2023-07-29T03:30:14.634,31,31,1,10,8,NaN,179000,8AM - 12PM

In [22]:
#create final dataframe with only the columns we want to include in our analysis

df_final = df_binned[['unique_id', 'tb_latitude', 'tb_longitude', 'collision_datetime', 'collision_time', 'accident_year', 'month', 'day_of_week', 'weather_1',
                       'collision_severity', 'type_of_collision', 'ped_action', 'control_device', 'number_killed', 'number_injured']]
df_final.head()

,unique_id,tb_latitude,tb_longitude,collision_datetime,collision_time,accident_year,month,day_of_week,weather_1,collision_severity,type_of_collision,ped_action,control_device,number_killed,number_injured
0,15414,37.777857,-122.406436,2015-11-18,9,2015,November,Wednesday,Clear,Injury (Complaint of Pain),Other,No Pedestrian Involved,None,0,1
1,52640,37.754453,-122.408343,2020-03-28,14,2020,March,Saturday,Cloudy,Injury (Other Visible),Broadside,No Pedestrian Involved,Functioning,0,1
2,36577,37.714040,-122.461135,2014-10-04,13,2014,October,Saturday,Clear,Injury (Complaint of Pain),Vehicle/Pedestrian,Not in Road,None,0,1
3,27582,37.791627,-122.402516,2016-09-08,14,2016,September,Thursday,Not Stated,Injury (Other Visible),Not Stated,Not Stated,Not Stated,0,1
4,14911,37.779856,-122.394008,2018-07-30,11,2018,July,Monday,Clear,Injury (Severe),Not Stated,No Pedestrian Involved,None,0,1

In [ ]:
# create an engine to access sql database file
engine = create_engine("sqlite:///data/traffic_db.sqlite")

# Convert the dataframe to a "data" table in the db.sqlite database
df_final.to_sql('traffic_db.sqlite', if_exists='replace', index=False, con=engine)